version: "3.5"

services:
  aee_digital_front:
    environment:
      - NODE_ENV=development
      - trabalho_api=trabalho_api
    build: https://github.com/brunoduartec/aee_digital_front.git
    command: npm start
    image: aee_digital_front
    container_name: aee_digital_front
    ports:
      - "4200:4200"
    networks:
      - aee_digital_backend
      - aee_trabalho_db
    volumes:
      - ./logs:/app/logs
    restart: always
networks:
  aee_digital_backend:
    external: true
  aee_trabalho_db:
    driver: bridge
