version: "3"

services:
  angular-ui:
    build:
      context: .
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - .:/usr/app/app-ui
       - /usr/app/app-ui/node_modules