version: "3"

services:
  aee_digital_front:
    build: .
    command: npm start
    image: aee_digital_front
    container_name: aee_digital_front
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/app