version: "3"

services:
  aee_digital_front:
    build:
      context: .
    ports:
      - "4200:4200"
    container_name: aee_digital_front
    image: aee_digital_front
    volumes:
      - .:/usr/app/app-ui
      - /usr/app/app-ui/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
