version: "3"

services:
  aee_tech_front:
    build:
      context: .
    ports:
      - "4200:4200"
    container_name: aee_tech_front
    image: aee_tech_front
    volumes:
       - .:/usr/app/app-ui
       - /usr/app/app-ui/node_modules